# docker-compose.yml
version: '3.8'

volumes:
  userdb_vol:

networks:
  micro_network:
    external:
      name: micro_network

services:
  user-api:
    container_name: cuser-service
    build:
      context: .
    ports:
    - "5001:5001"
    depends_on:
      - user-db
    networks:
      - micro_network
    restart: always

  user-db:
    container_name: cuser_dbase
    image: postgres:latest
    ports:
    - "32000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mango42
      POSTGRES_DB: user
    networks:
      - micro_network
    volumes:
    - userdb_vol:/var/lib/postgresql/data